spring.application.name=ecomerce
spring.datasource.url=jdbc:mysql://localhost:3306/ecomerce
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.secret=thG5OAKuIKpbgMnGGZniFQnoIwbtI4iu7pm/vfvfuLS78K+chRUoO6MWWT/2bHfcM+hErbv9XVheikQ7xIMvWZIb35IIqFe9mYGKu/C0Tm/pNC8h0RUPqnM7I4+rrBUiF8EVzOGOWFEGuEyOsMH4RNDjXDxI4xbxQjPdfU6+z2g=
jwt.expiration=86400000
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
